return {
  KEY_MAP = {
    ["`~"] = Key.OEM_3,
    ["1!"] = Key.DIGIT_1,
    ["2@"] = Key.DIGIT_2,
    ["3#"] = Key.DIGIT_3,
    ["4$"] = Key.DIGIT_4,
    ["5%"] = Key.DIGIT_5,
    ["6^"] = Key.DIGIT_6,
    ["7&"] = Key.DIGIT_7,
    ["8*"] = Key.DIGIT_8,
    ["9("] = Key.DIGIT_9,
    ["0)"] = Key.DIGIT_0,
    ["-_"] = Key.OEM_MINUS,
    ["=+"] = Key.OEM_PLUS,

    ["Q"] = Key.Q,
    ["W"] = Key.W,
    ["E"] = Key.E,
    ["R"] = Key.R,
    ["T"] = Key.T,
    ["Y"] = Key.Y,
    ["U"] = Key.U,
    ["I"] = Key.I,
    ["O"] = Key.O,
    ["P"] = Key.P,
    ["[{"] = Key.OEM_4,
    ["]}"] = Key.OEM_6,
    ["\\|"] = Key.OEM_5,

    ["A"] = Key.A,
    ["S"] = Key.S,
    ["D"] = Key.D,
    ["F"] = Key.F,
    ["G"] = Key.G,
    ["H"] = Key.H,
    ["J"] = Key.J,
    ["K"] = Key.K,
    ["L"] = Key.L,
    [";:"] = Key.OEM_1,
    ["'\""] = Key.OEM_7,

    ["Z"] = Key.Z,
    ["X"] = Key.X,
    ["C"] = Key.C,
    ["V"] = Key.V,
    ["B"] = Key.B,
    ["N"] = Key.N,
    ["M"] = Key.M,
    [",<"] = Key.OEM_COMMA,
    [".>"] = Key.OEM_PERIOD,
    ["/?"] = Key.OEM_2,

    ["Escape"] = Key.ESCAPE,
    ["F1"] = Key.F1,
    ["F2"] = Key.F2,
    ["F3"] = Key.F3,
    ["F4"] = Key.F4,
    ["F5"] = Key.F5,
    ["F6"] = Key.F6,
    ["F7"] = Key.F7,
    ["F8"] = Key.F8,
    ["F9"] = Key.F9,
    ["F10"] = Key.F10,
    ["F11"] = Key.F11,
    ["F12"] = Key.F12,
    ["F13"] = Key.F13,
    ["F14"] = Key.F14,
    ["F15"] = Key.F15,
    ["F16"] = Key.F16,
    ["F17"] = Key.F17,
    ["F18"] = Key.F18,
    ["F19"] = Key.F19,
    ["F20"] = Key.F20,
    ["F21"] = Key.F21,
    ["F22"] = Key.F22,
    ["F23"] = Key.F23,

    ["Backspace"] = Key.BACK,
    ["Tab"] = Key.TAB,
    ["Enter"] = Key.RETURN,
    ["CapsLock"] = Key.CAPITAL,
    ["Space"] = Key.SPACE,
    ["ContextMenu"] = Key.APPS,

    ["PrintScreen"] = Key.SNAPSHOT,
    ["ScrollLock"] = Key.SCROLL,
    ["Pause"] = Key.PAUSE,
    ["Insert"] = Key.INSERT,
    ["Home"] = Key.HOME,
    ["PageUp"] = Key.PRIOR,
    ["Delete"] = Key.DELETE,
    ["End"] = Key.END,
    ["PageDown"] = Key.NEXT,
    ["Up"] = Key.UP,
    ["Down"] = Key.DOWN,
    ["Left"] = Key.LEFT,
    ["Right"] = Key.RIGHT,

    ["NumLock"] = Key.NUMLOCK,
    ["Numpad0"] = Key.NUMPAD0,
    ["Numpad1"] = Key.NUMPAD1,
    ["Numpad2"] = Key.NUMPAD2,
    ["Numpad3"] = Key.NUMPAD3,
    ["Numpad4"] = Key.NUMPAD4,
    ["Numpad5"] = Key.NUMPAD5,
    ["Numpad6"] = Key.NUMPAD6,
    ["Numpad7"] = Key.NUMPAD7,
    ["Numpad8"] = Key.NUMPAD8,
    ["Numpad9"] = Key.NUMPAD9,
    ["NumpadDecimal"] = Key.DECIMAL,
    ["NumpadAdd"] = Key.ADD,
    ["NumpadSubtract"] = Key.SUBTRACT,
    ["NumpadMultiply"] = Key.MULTIPLY,
    ["NumpadDivide"] = Key.DIVIDE,
    ["NumpadEnter"] = Key.NUMPAD_RETURN,

    ["ShiftLeft"] = Key.LSHIFT,
    ["ControlLeft"] = Key.LCONTROL,
    ["AltLeft"] = Key.LMENU,
    ["OSLeft"] = Key.LWIN,
    ["ShiftRight"] = Key.RSHIFT,
    ["ControlRight"] = Key.RCONTROL,
    ["AltRight"] = Key.RMENU,
    ["OSRight"] = Key.RWIN,
  },
  ALPHANUMERIC_KEYS = {
    Key.OEM_3, Key.DIGIT_1, Key.DIGIT_2, Key.DIGIT_3, Key.DIGIT_4, Key.DIGIT_5, Key.DIGIT_6, Key.DIGIT_7, Key.DIGIT_8, Key.DIGIT_9, Key.DIGIT_0, Key.OEM_MINUS, Key.OEM_PLUS,
    Key.Q, Key.W, Key.E, Key.R, Key.T, Key.Y, Key.U, Key.I, Key.O, Key.P, Key.OEM_4, Key.OEM_6, Key.OEM_5,
    Key.A, Key.S, Key.D, Key.F, Key.G, Key.H, Key.J, Key.K, Key.L, Key.OEM_1, Key.OEM_7,
    Key.Z, Key.X, Key.C, Key.V, Key.B, Key.N, Key.M, Key.OEM_COMMA, Key.OEM_PERIOD, Key.OEM_2,
  },
  NON_ALPHANUMERIC_KEYS = {
    Key.ESCAPE, Key.F1, Key.F2, Key.F3, Key.F4, Key.F5, Key.F6, Key.F7, Key.F8, Key.F9, Key.F10, Key.F11, Key.F12, Key.F13, Key.F14, Key.F15, Key.F16, Key.F17, Key.F18, Key.F19, Key.F20, Key.F21, Key.F22, Key.F23, Key.F24,
    Key.BACK, Key.TAB, Key.RETURN, Key.CAPITAL, Key.SPACE, Key.APPS,
    Key.SNAPSHOT, Key.SCROLL, Key.PAUSE, Key.INSERT, Key.HOME, Key.PRIOR, Key.DELETE, Key.END, Key.NEXT, Key.UP, Key.DOWN, Key.LEFT, Key.RIGHT,
    Key.NUMLOCK, Key.NUMPAD0, Key.NUMPAD1, Key.NUMPAD2, Key.NUMPAD3, Key.NUMPAD4, Key.NUMPAD5, Key.NUMPAD6, Key.NUMPAD7, Key.NUMPAD8, Key.NUMPAD9, Key.DECIMAL, Key.ADD, Key.SUBTRACT, Key.MULTIPLY, Key.DIVIDE, Key.NUMPAD_RETURN,
  },
  MODIFIER_KEYS = {
    Key.LSHIFT, Key.LCONTROL, Key.LMENU, Key.LWIN,
    Key.RSHIFT, Key.RCONTROL, Key.RMENU, Key.RWIN,
  },
}
