return {
  ACTIONS_MAP = {
    ["`"] = {{Key.GRAVE}},
    ["1"] = {{Key.DIGIT_1}},
    ["2"] = {{Key.DIGIT_2}},
    ["3"] = {{Key.DIGIT_3}},
    ["4"] = {{Key.DIGIT_4}},
    ["5"] = {{Key.DIGIT_5}},
    ["6"] = {{Key.DIGIT_6}},
    ["7"] = {{Key.DIGIT_7}},
    ["8"] = {{Key.DIGIT_8}},
    ["9"] = {{Key.DIGIT_9}},
    ["0"] = {{Key.DIGIT_0}},
    ["-"] = {{Key.MINUS}},
    ["="] = {{Key.EQUAL}},

    ["q"] = {{Key.Q}},
    ["w"] = {{Key.W}},
    ["e"] = {{Key.E}},
    ["r"] = {{Key.R}},
    ["t"] = {{Key.T}},
    ["y"] = {{Key.Y}},
    ["u"] = {{Key.U}},
    ["i"] = {{Key.I}},
    ["o"] = {{Key.O}},
    ["p"] = {{Key.P}},
    ["["] = {{Key.LEFTBRACE}},
    ["]"] = {{Key.RIGHTBRACE}},
    ["\\"] = {{Key.BACKSLASH}},

    ["a"] = {{Key.A}},
    ["s"] = {{Key.S}},
    ["d"] = {{Key.D}},
    ["f"] = {{Key.F}},
    ["g"] = {{Key.G}},
    ["h"] = {{Key.H}},
    ["j"] = {{Key.J}},
    ["k"] = {{Key.K}},
    ["l"] = {{Key.L}},
    [";"] = {{Key.SEMICOLON}},
    ["'"] = {{Key.APOSTROPHE}},

    ["z"] = {{Key.Z}},
    ["x"] = {{Key.X}},
    ["c"] = {{Key.C}},
    ["v"] = {{Key.V}},
    ["b"] = {{Key.B}},
    ["n"] = {{Key.N}},
    ["m"] = {{Key.M}},
    [","] = {{Key.COMMA}},
    ["."] = {{Key.DOT}},
    ["/"] = {{Key.SLASH}},

    ["~"] = {{Key.GRAVE, Mod.SHIFT}},
    ["!"] = {{Key.DIGIT_1, Mod.SHIFT}},
    ["@"] = {{Key.DIGIT_2, Mod.SHIFT}},
    ["#"] = {{Key.DIGIT_3, Mod.SHIFT}},
    ["$"] = {{Key.DIGIT_4, Mod.SHIFT}},
    ["%"] = {{Key.DIGIT_5, Mod.SHIFT}},
    ["^"] = {{Key.DIGIT_6, Mod.SHIFT}},
    ["&"] = {{Key.DIGIT_7, Mod.SHIFT}},
    ["*"] = {{Key.DIGIT_8, Mod.SHIFT}},
    ["("] = {{Key.DIGIT_9, Mod.SHIFT}},
    [")"] = {{Key.DIGIT_0, Mod.SHIFT}},
    ["_"] = {{Key.MINUS, Mod.SHIFT}},
    ["+"] = {{Key.EQUAL, Mod.SHIFT}},

    ["Q"] = {{Key.Q, Mod.SHIFT}},
    ["W"] = {{Key.W, Mod.SHIFT}},
    ["E"] = {{Key.E, Mod.SHIFT}},
    ["R"] = {{Key.R, Mod.SHIFT}},
    ["T"] = {{Key.T, Mod.SHIFT}},
    ["Y"] = {{Key.Y, Mod.SHIFT}},
    ["U"] = {{Key.U, Mod.SHIFT}},
    ["I"] = {{Key.I, Mod.SHIFT}},
    ["O"] = {{Key.O, Mod.SHIFT}},
    ["P"] = {{Key.P, Mod.SHIFT}},
    ["{"] = {{Key.LEFTBRACE, Mod.SHIFT}},
    ["}"] = {{Key.RIGHTBRACE, Mod.SHIFT}},
    ["|"] = {{Key.BACKSLASH, Mod.SHIFT}},

    ["A"] = {{Key.A, Mod.SHIFT}},
    ["S"] = {{Key.S, Mod.SHIFT}},
    ["D"] = {{Key.D, Mod.SHIFT}},
    ["F"] = {{Key.F, Mod.SHIFT}},
    ["G"] = {{Key.G, Mod.SHIFT}},
    ["H"] = {{Key.H, Mod.SHIFT}},
    ["J"] = {{Key.J, Mod.SHIFT}},
    ["K"] = {{Key.K, Mod.SHIFT}},
    ["L"] = {{Key.L, Mod.SHIFT}},
    [":"] = {{Key.SEMICOLON, Mod.SHIFT}},
    ["\""] = {{Key.APOSTROPHE, Mod.SHIFT}},

    ["Z"] = {{Key.Z, Mod.SHIFT}},
    ["X"] = {{Key.X, Mod.SHIFT}},
    ["C"] = {{Key.C, Mod.SHIFT}},
    ["V"] = {{Key.V, Mod.SHIFT}},
    ["B"] = {{Key.B, Mod.SHIFT}},
    ["N"] = {{Key.N, Mod.SHIFT}},
    ["M"] = {{Key.M, Mod.SHIFT}},
    ["<"] = {{Key.COMMA, Mod.SHIFT}},
    [">"] = {{Key.DOT, Mod.SHIFT}},
    ["?"] = {{Key.SLASH, Mod.SHIFT}},

    ["\\|"] = {{Key.BACKSLASH}},
    ["\\_"] = {{Key.BACKSLASH}},
    ["Shift+0"] = {{Key.DIGIT_0, Mod.SHIFT}},

    ["Escape"] = {{Key.ESC}},
    ["F1"] = {{Key.F1}},
    ["F2"] = {{Key.F2}},
    ["F3"] = {{Key.F3}},
    ["F4"] = {{Key.F4}},
    ["F5"] = {{Key.F5}},
    ["F6"] = {{Key.F6}},
    ["F7"] = {{Key.F7}},
    ["F8"] = {{Key.F8}},
    ["F9"] = {{Key.F9}},
    ["F10"] = {{Key.F10}},
    ["F11"] = {{Key.F11}},
    ["F12"] = {{Key.F12}},
    ["F13"] = {{Key.F13}},
    ["F14"] = {{Key.F14}},
    ["F15"] = {{Key.F15}},
    ["F16"] = {{Key.F16}},
    ["F17"] = {{Key.F17}},
    ["F18"] = {{Key.F18}},
    ["F19"] = {{Key.F19}},
    ["F20"] = {{Key.F20}},
    ["F21"] = {{Key.F21}},
    ["F22"] = {{Key.F22}},
    ["F23"] = {{Key.F23}},
    ["F24"] = {{Key.F24}},

    ["Backspace"] = {{Key.BACKSPACE}},
    ["Tab"] = {{Key.TAB}},
    ["Enter"] = {{Key.ENTER}},
    ["CapsLock"] = {{Key.CAPSLOCK}},
    ["Space"] = {{Key.SPACE}},
    ["ContextMenu"] = {{Key.COMPOSE}},

    ["PrintScreen"] = {{Key.SYSRQ}},
    ["ScrollLock"] = {{Key.SCROLLLOCK}},
    ["Pause"] = {{Key.PAUSE}},
    ["Insert"] = {{Key.INSERT}},
    ["Home"] = {{Key.HOME}},
    ["PageUp"] = {{Key.PAGEUP}},
    ["Delete"] = {{Key.DELETE}},
    ["End"] = {{Key.END}},
    ["PageDown"] = {{Key.PAGEDOWN}},

    ["Up"] = {{Key.UP}},
    ["Left"] = {{Key.LEFT}},
    ["Down"] = {{Key.DOWN}},
    ["Right"] = {{Key.RIGHT}},

    ["NumLock"] = {{Key.NUMLOCK}},
    ["Numpad0"] = {{Key.KP0}},
    ["Numpad1"] = {{Key.KP1}},
    ["Numpad2"] = {{Key.KP2}},
    ["Numpad3"] = {{Key.KP3}},
    ["Numpad4"] = {{Key.KP4}},
    ["Numpad5"] = {{Key.KP5}},
    ["Numpad6"] = {{Key.KP6}},
    ["Numpad7"] = {{Key.KP7}},
    ["Numpad8"] = {{Key.KP8}},
    ["Numpad9"] = {{Key.KP9}},
    ["NumpadDecimal"] = {{Key.KPDOT}},
    ["NumpadAdd"] = {{Key.KPPLUS}},
    ["NumpadSubtract"] = {{Key.KPMINUS}},
    ["NumpadMultiply"] = {{Key.KPASTERRISK}},
    ["NumpadDivide"] = {{Key.KPSLASH}},
    ["NumpadEnter"] = {{Key.KPENTER}},

    ["ShiftLeft"] = {{0, Mod.SHIFT_LEFT}},
    ["ControlLeft"] = {{0, Mod.CONTROL_LEFT}},
    ["AltLeft"] = {{0, Mod.ALT_LEFT}},
    ["OSLeft"] = {{0, Key.OS_LEFT}},
    ["ShiftRight"] = {{0, Mod.SHIFT_RIGHT}},
    ["ControlRight"] = {{0, Mod.CONTROL_RIGHT}},
    ["AltRight"] = {{0, Mod.ALT_RIGHT}},
    ["OSRight"] = {{0, Mod.OS_RIGHT}},
  },
}
